package edu.orsys.jee.tests;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GestionPerimetresTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
		System.setProperty("webdriver.chrome.driver", "c:/users/chromedriver.exe");
		ChromeOptions chromeOptions = new ChromeOptions();
		chromeOptions.addArguments("headless");
		driver = new ChromeDriver(chromeOptions);
	    js = (JavascriptExecutor) driver;
	    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void fT00201() {
    driver.get("http://localhost:8080/Projet-JEE-CAMACHO/");
    driver.findElement(By.id("login")).sendKeys("hugo31");
    driver.findElement(By.id("pwd")).sendKeys("toto");
    driver.findElement(By.id("pwd")).sendKeys(Keys.ENTER);
    assertThat(driver.getTitle(), is("Bienvenue administrateur!"));
  }
  @Test
  public void fT00202() {
    driver.get("http://localhost:8080/Projet-JEE-CAMACHO/");
    driver.findElement(By.id("login")).sendKeys("hugo31");
    driver.findElement(By.id("pwd")).sendKeys("toto");
    driver.findElement(By.id("pwd")).sendKeys(Keys.ENTER);
    assertThat(driver.getTitle(), is("Bienvenue administrateur!"));
    driver.findElement(By.linkText("Vers la gestion de vos perimetres")).click();
    assertThat(driver.getTitle(), is("Gestion des perimetres"));
  }
  @Test
  public void fT00203() {
    driver.get("http://localhost:8080/Projet-JEE-CAMACHO/");
    driver.findElement(By.id("login")).sendKeys("hugo31");
    driver.findElement(By.id("pwd")).sendKeys("toto");
    driver.findElement(By.id("pwd")).sendKeys(Keys.ENTER);
    assertThat(driver.getTitle(), is("Bienvenue administrateur!"));
    driver.findElement(By.linkText("Vers la gestion de vos perimetres")).click();
    driver.findElement(By.linkText("Ajouter un perimetre...")).click();
    assertThat(driver.getTitle(), is("Ajout d\'un perimetre"));
  }
  @Test
  public void fT00204() {
    driver.get("http://localhost:8080/Projet-JEE-CAMACHO/");
    driver.findElement(By.id("login")).sendKeys("hugo31");
    driver.findElement(By.id("pwd")).sendKeys("toto");
    driver.findElement(By.id("pwd")).sendKeys(Keys.ENTER);
    assertThat(driver.getTitle(), is("Bienvenue administrateur!"));
    driver.findElement(By.linkText("Vers la gestion de vos perimetres")).click();
    driver.findElement(By.linkText("Ajouter un perimetre...")).click();
    assertThat(driver.getTitle(), is("Ajout d\'un perimetre"));
    driver.findElement(By.id("nom_perim")).click();
    driver.findElement(By.id("nom_perim")).sendKeys("testperim");
    driver.findElement(By.id("Acrobat")).click();
    driver.findElement(By.id("Flash Player")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) b")).getText(), is("testperim"));
  }
  @Test
  public void fT00205() {
    driver.get("http://localhost:8080/Projet-JEE-CAMACHO/");
    driver.findElement(By.id("login")).sendKeys("hugo31");
    driver.findElement(By.id("pwd")).sendKeys("toto");
    driver.findElement(By.id("pwd")).sendKeys(Keys.ENTER);
    assertThat(driver.getTitle(), is("Bienvenue administrateur!"));
    driver.findElement(By.linkText("Vers la gestion de vos perimetres")).click();
    driver.findElement(By.linkText("Ajouter un perimetre...")).click();
    assertThat(driver.getTitle(), is("Ajout d\'un perimetre"));
    driver.findElement(By.id("nom_perim")).click();
    driver.findElement(By.id("nom_perim")).sendKeys("testperim");
    driver.findElement(By.id("Acrobat")).click();
    driver.findElement(By.id("Flash Player")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//b[contains(.,\'testperim\')]"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(3) > a")).click();
    driver.findElement(By.cssSelector("html")).click();
    assertThat(driver.getTitle(), is("Gestion des perimetres"));
    {
      List<WebElement> elements = driver.findElements(By.xpath("//b[contains(.,\'testperim\')]"));
      assert(elements.size() == 0);
    }
  }
}
